version: '3.8'

services:
  app:
    container_name: sample-app1
    build:
      context: ./vue
      dockerfile: Dockerfile.prod
    networks:
      - app_bridge

networks:
  app_bridge:
    external: true
