FROM node:lts-alpine as build-stage
WORKDIR /app
COPY ./src/package*.json ./
COPY ./src/yarn.lock ./
RUN yarn global add @vue/cli

RUN yarn install

COPY ./src .
COPY ./src/dot.env ./.env
RUN yarn build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]