version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: sample-proxy
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - app_bridge

networks:
  app_bridge:
    external: true
